version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node 
    ports:
      - 9200:9200
  kibana:
    image: gradiant/kibana-oss:7.5.0
    ports:
      - 5601:5601
